// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vdom = require("../src-ocaml/vdom.js");
var Curry = require("rescript/lib/js/curry.js");
var Tea_ex = require("../src-ocaml/tea_ex.js");
var Tea_html = require("../src-ocaml/tea_html.js");
var Tea_http = require("../src-ocaml/tea_http.js");
var Tea_task = require("../src-ocaml/tea_task.js");
var Tea_debug = require("../src-ocaml/tea_debug.js");

function gotResponse(param_0) {
  return /* GotResponse */{
          _0: param_0
        };
}

function update(model, param) {
  if (param) {
    return [
            param._0._0,
            /* NoCmd */0
          ];
  } else {
    return [
            model,
            Tea_task.attempt(gotResponse, Tea_task.andThen((function (param) {
                        return /* Task */{
                                _0: (function (cb) {
                                    return Curry._1(cb, {
                                                TAG: /* Ok */0,
                                                _0: "both saved"
                                              });
                                  })
                              };
                      }), Tea_task.andThen((function (res) {
                            return Tea_ex.LocalStorage.setItem("todo-2", res);
                          }), Tea_task.andThen((function (param) {
                                return Tea_task.mapError(Tea_http.string_of_error, Tea_http.toTask(Tea_http.getString("https://jsonplaceholder.typicode.com/todos/2")));
                              }), Tea_task.andThen((function (res) {
                                    return Tea_ex.LocalStorage.setItem("todo-1", res);
                                  }), Tea_task.mapError(Tea_http.string_of_error, Tea_http.toTask(Tea_http.getString("https://jsonplaceholder.typicode.com/todos/1"))))))))
          ];
  }
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* [] */0, {
              hd: Tea_html.button(undefined, undefined, {
                    hd: Vdom.onMsg("click", /* Req */0),
                    tl: /* [] */0
                  }, {
                    hd: {
                      TAG: /* Text */1,
                      _0: "execute"
                    },
                    tl: /* [] */0
                  }),
              tl: {
                hd: {
                  TAG: /* Text */1,
                  _0: model
                },
                tl: /* [] */0
              }
            });
}

function som(param) {
  if (param) {
    if (param._0.TAG === /* Ok */0) {
      return "GotResponse Ok";
    } else {
      return "GotResponse Error";
    }
  } else {
    return "Req";
  }
}

function partial_arg_init(param) {
  return [
          "nothing",
          /* NoCmd */0
        ];
}

function partial_arg_subscriptions(param) {
  return /* NoSub */0;
}

var partial_arg = {
  init: partial_arg_init,
  update: update,
  view: view,
  subscriptions: partial_arg_subscriptions
};

function main(param, param$1) {
  return Tea_debug.standardProgram(partial_arg, som, param, param$1);
}

var req = /* Req */0;

exports.gotResponse = gotResponse;
exports.req = req;
exports.update = update;
exports.view = view;
exports.som = som;
exports.main = main;
/* Tea_html Not a pure module */
